// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkoxvhgsnjgsnpzbfrfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rb3h2aGdzbmpnc25wemJmcmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTUyNjgsImV4cCI6MjA3MTA5MTI2OH0.oXnxKHp3ulDgkp897BHbuy8zjALFIYfXZzBvZglClsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});